sonar.projectKey=oficina-os-service
sonar.projectName=oficina-os-service
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=src/**/*.spec.ts,test/**/*.ts
sonar.exclusions=src/**/*.spec.ts,src/**/*.module.ts,src/**/*.dto.ts
sonar.coverage.exclusions=src/main.ts,src/common/enums/**,src/prisma/prisma.service.ts,src/result/**
sonar.cpd.exclusions=test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
